[versions]
neogradle = "6.+"
mixingradle = "0.7.+"
librarian = "1.+"

neoforge = "1.20.1-47.1.104"

curios = "5266541"

caelus = "3.2.0+1.20.1"

cameraoverhaul = "4057605"

[libraries]
neoforge = { module = "net.neoforged:forge", version.ref = "neoforge" }

curios = { module = "curse.maven:curios-309927", version.ref = "curios" }

caelus = { module = "top.theillusivec4.caelus:caelus-forge", version.ref = "caelus" }

cameraoverhaul = { module = "curse.maven:camera-overhaul-forge-443034", version.ref = "cameraoverhaul" }

[plugins]
neogradle = { id = "net.neoforged.gradle", version.ref = "neogradle" }
mixingradle = { id = "org.spongepowered.mixin", version.ref = "mixingradle" }
librarian = { id = "org.parchmentmc.librarian.forgegradle", version.ref = "librarian" }
