[versions]
neogradle = "7.0.120"

neoforge = "20.4.237"

curios = "7.4.3+1.20.4"

caelus = "5.1.0+1.20.4"

cameraoverhaul = "5416786"

[libraries]
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

curios = { module = "top.theillusivec4.curios:curios-neoforge", version.ref = "curios" }

caelus = { module = "top.theillusivec4.caelus:caelus-neoforge", version.ref = "caelus" }

cameraoverhaul = { module = "curse.maven:camera-overhaul-reforged-1011593", version.ref = "cameraoverhaul" }

[plugins]
neogradle = { id = "net.neoforged.gradle.userdev", version.ref = "neogradle" }
